language: node_js
node_js:
  - "stable"
cache:
  directories:
  - website/node_modules
script:
  - yarn build 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: website/build
  on:
    branch: master